In [15]:
import pymatgen
import numpy as np
import pandas as pd
import chemparse
from scipy.spatial import ConvexHull
import math 
import random
import ast


In [26]:
pd.options.display.max_colwidth = 10000

netarray = pd.read_csv('netarray727.csv', header=None)
fulldset = pd.read_csv('fulldataset.csv')
oxidemelt =  pd.read_csv('oxides_data_meltpoint.csv').iloc[:,1:]
oxide_melt = np.array(oxidemelt.drop_duplicates(subset='chemical_formula', keep='first'))


In [74]:
oxideenergy = netarray[0]
initialmass = netarray[1]
finalmass = netarray[2]
oxideweights = netarray[3]
elements = netarray[4]
matrixcomp = netarray[5]
oxidenames = netarray[6]


C:\Users\songo\AppData\Local\Temp\ipykernel_16848\2551494189.py:12: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  oxidenames = np.array(temp)


In [318]:
temp = []
for name in oxidenames:
    replaced = np.array(ast.literal_eval((name.replace(' ',','))))
    temp.append(replaced)
oxidenames = np.array(temp)

material_melt = fulldset['Oxide Melt Temp']

C:\Users\songo\AppData\Local\Temp\ipykernel_16848\1421179352.py:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  oxidenames = np.array(temp)


In [81]:
temp = []
for id in range(len(oxideenergy)):
    foundindices = np.where(np.isin(oxide_melt[:,0], oxidenames[id]))
    melttemps = np.array(oxide_melt[foundindices])
    percents = oxideweights[id]
    temp.append([oxidenames[id], percents, melttemps])
    

In [103]:
periodictable = np.array(pd.read_csv('PeriodicTableCleaned_data.csv'))
temp = np.array(temp)

In [89]:
melt_names = temp[:,0]
melt_amounts = temp[:,1]
melt_heats = temp[:,2]

In [ ]:
melt_names

In [135]:
netmass = []
names = np.array(fulldset['Superconductor'])

for materialname in np.array(fulldset['Superconductor']):
    keys = np.asarray(list(chemparse.parse_formula(materialname).keys()))
    values = np.asarray(list(chemparse.parse_formula(materialname).values()))
    # mass_indices = np.argwhere(np.isin(periodictable[:,0], keys))
    masses = []
    for i in keys:
        masses.append(periodictable[:,7][np.argwhere(periodictable[:,0]==i)])
    masses = np.array(masses)
    netmass_entry = np.dot(masses.T, values)
    netmass.append(netmass_entry)

    

In [137]:
netmass = np.array(netmass)

test = []
for id in melt_amounts:
    test.append(np.array(ast.literal_eval((((((id.replace('\n', '')).replace('  ',',')).replace(' -',',-')).replace(' ', ',')).replace('[,','[')).replace(',,',',').replace(',,',',').replace(',,',',').replace(',,',','))))

In [153]:
melt_amounts = np.array(test)

C:\Users\songo\AppData\Local\Temp\ipykernel_16848\759685881.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  melt_amounts = np.array(test)


In [293]:
test2 = []
for id in range(len(matrixcomp)):
    test2.append(np.array(ast.literal_eval((((((matrixcomp[id].replace('\n', '')).replace('  ',',')).replace(' -',',-')).replace(' ', ',')).replace('[,','[')).replace(',,',',').replace(',,',',').replace(',,',',').replace(',,',','))))


In [305]:
matrixcomp = np.array(test2)

C:\Users\songo\AppData\Local\Temp\ipykernel_16848\1148871628.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  matrixcomp = np.array(test2)


In [301]:
test3 = []
for id in range(len(oxideweights)):
    test3.append(np.array(ast.literal_eval((((((oxideweights[id].replace('\n', '')).replace('  ',',')).replace(' -',',-')).replace(' ', ',')).replace('[,','[')).replace(',,',',').replace(',,',',').replace(',,',',').replace(',,',','))))


In [302]:
oxideweights = np.array(test3)

C:\Users\songo\AppData\Local\Temp\ipykernel_16848\3145140095.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  oxideweights = np.array(test3)


In [308]:
finalmass = [np.dot(matrixcomp[id].T, oxideweights[id]) for id in range(len(oxideweights))]

In [327]:
meltingtemperatures = []
for id in range(len(oxidenames)):
    meltlist = []
    oxidelist = oxidenames[id]
    heatsnames = melt_heats[id][:,0]
    heatstemps = melt_heats[id][:,1]
    for oxide in oxidelist:
        index = np.where(heatsnames == oxide)
        meltlist.append(heatstemps[index])
    meltlist = np.array(meltlist)
    meltingtemperatures.append(meltlist)
meltingtemperatures = np.array(meltingtemperatures)

C:\Users\songo\AppData\Local\Temp\ipykernel_16848\2645317297.py:12: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  meltingtemperatures = np.array(meltingtemperatures)


In [346]:
temp4 = []
for id in elements:
    temp4.append(ast.literal_eval(id))

C:\Users\songo\AppData\Local\Temp\ipykernel_16848\3212173579.py:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  elements = np.array(test)


In [352]:
elements = np.array(temp4)

C:\Users\songo\AppData\Local\Temp\ipykernel_16848\2635957228.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  elements = np.array(temp4)


In [358]:
elements[2]

['Sb', 'S', 'F', 'O']

In [359]:
elementmasses = []
for lists in elements:
    tempmasses = []
    for elementid in range(len(lists)-1):
        tempmasses.append(periodictable[:,7][np.where(periodictable[:,0]==lists[elementid])])
    tempmasses = np.array(tempmasses)
    elementmasses.append(tempmasses)
elementmasses = np.array(elementmasses)

C:\Users\songo\AppData\Local\Temp\ipykernel_16848\3074387746.py:8: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  elementmasses = np.array(elementmasses)


In [403]:
elementmasses

array([array([[6.94],
              [40.0784],
              [207.21]], dtype=object), array([[55.8452],
                                               [10.81]], dtype=object),
       array([[121.7601],
              [32.06],
              [18.99840316]], dtype=object), ...,
       array([[92.906372],
              [106.421]], dtype=object), array([[92.906372],
                                                [106.421]], dtype=object),
       array([[55.8452],
              [78.9718],
              [127.603]], dtype=object)], dtype=object)

In [407]:
oxidemasses = []
for id in range(len(material_melt)):
    material_meltingtemp = material_melt[id]
    names = oxidenames[id]
    matrixs = matrixcomp[id]
    weights = oxideweights[id]
    meltingtemps = meltingtemperatures[id]
    tempweights = weights*0
    for oxideid in range(len(weights)):
        if float(meltingtemps[oxideid]) < float(material_meltingtemp):
            tempweights[oxideid] += weights[oxideid]
    tempmass = np.dot(matrixs.T, tempweights)
    oxidemasses.append(tempmass)
oxidemasses = np.array(oxidemasses)

C:\Users\songo\AppData\Local\Temp\ipykernel_16848\2310499121.py:14: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  oxidemasses = np.array(oxidemasses)


In [427]:
resid = finalmass-oxidemasses

C:\Users\songo\AppData\Local\Temp\ipykernel_16848\2154905089.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  resid = finalmass-oxidemasses


In [431]:
finalmass[7]

array([1.00000008, 1.00000002, 1.00000011, 6.00000018])

In [433]:
oxideweights[7]

array([ 0.05181403,  0.16116333,  0.04557991,  0.08492571,  0.0393458 ,
       -0.00623412, -0.06428226,  0.10362806, -0.12294197, -0.05804814,
        0.05181403, -0.00684568,  0.08186787, -0.08707222,  0.04435678,
        0.07399242, -0.02902407, -0.11609629, -0.02902407,  0.04435678,
        0.08186787, -0.02902407,  0.02217839,  0.05181403,  0.0283029 ,
        0.02217839,  0.02217839, -0.00684568,  0.04245435, -0.02902407,
        0.01415145,  0.        ])

In [409]:
percentages = []
percentages_test = []
finalmasses_AU = []
oxidemasses_AU = []
for id in range(len(oxidemasses)):
    totalmass = finalmass[id]
    oxidemass = oxidemasses[id]
    testmass = totalmass - oxidemass
    elementmass = elementmasses[id]
    totalmass_AU = 0
    oxidemass_AU = 0
    testmass_AU = 0
    for i in range(len(totalmass)):
        totalmass_AU += elementmass[i] * totalmass[i]
        oxidemass_AU += elementmass[i] * oxidemass[i]
        testmass_AU += testmass[i] * elementmass[i]
    testtestmass_AU = totalmass_AU - testmass_AU
    finalmasses_AU.append(totalmass_AU)
    oxidemasses_AU.append(oxidemass_AU)
    if totalmass_AU == 0:
        percentages.append(0)
        percentages_test.append(0)
    else:
        percentages.append(oxidemass_AU / totalmass_AU)
        percentages_test.append(testtestmass_AU / totalmass_AU)
percentages = np.array(percentages)
percentages_test = np.array(percentages_test)
finalmasses_AU = np.array(finalmasses_AU)
oxidemasses_AU = np.array(oxidemasses_AU)

C:\Users\songo\AppData\Local\Temp\ipykernel_16848\2580632224.py:26: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  percentages = np.array(percentages)
C:\Users\songo\AppData\Local\Temp\ipykernel_16848\2580632224.py:27: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  percentages_test = np.array(percentages_test)


In [417]:
np.savetxt('oxidemelted_percentages.csv', percentages, delimiter=',')
np.savetxt('oxidemelted_finalmasses.csv', finalmasses_AU, delimiter=',')
np.savetxt('oxidemelted_oxidemasses.csv', oxidemasses_AU, delimiter=',')


In [420]:
percent = np.loadtxt('oxidemelted_percentages.csv')

In [422]:
percentages[0:20]

array([array([0.7252634133167576], dtype=object),
       array([0.0], dtype=object), array([1.0], dtype=object),
       array([0.547817638836617], dtype=object),
       array([0.6294424231407163], dtype=object),
       array([0.2140743884395292], dtype=object),
       array([0.001456792772122397], dtype=object),
       array([1.0696325157171447], dtype=object),
       array([0.2169655596972843], dtype=object),
       array([0.4485118520833329], dtype=object),
       array([0.21363142479762331], dtype=object),
       array([0.863261200296546], dtype=object),
       array([3.7284513727124945e-08], dtype=object),
       array([0.981964824861955], dtype=object),
       array([1.1591764549803754], dtype=object),
       array([1.5706775976049712], dtype=object),
       array([1.204504231912251], dtype=object),
       array([0.2586119344400126], dtype=object),
       array([1.0], dtype=object),
       array([0.02493946155073444], dtype=object)], dtype=object)

In [423]:
percent[0:20]

array([7.25263413e-01, 0.00000000e+00, 1.00000000e+00, 5.47817639e-01,
       6.29442423e-01, 2.14074388e-01, 1.45679277e-03, 1.06963252e+00,
       2.16965560e-01, 4.48511852e-01, 2.13631425e-01, 8.63261200e-01,
       3.72845137e-08, 9.81964825e-01, 1.15917645e+00, 1.57067760e+00,
       1.20450423e+00, 2.58611934e-01, 1.00000000e+00, 2.49394616e-02])

In [261]:
meltingmass = []
for id in range(1000):
    material_meltingtemp = material_melt[id]    
    # meltingnames = np.array(ast.literal_eval(((melt_names[id].replace('\n', '')).replace(' ',','))))
    # meltingamounts = np.array(ast.literal_eval((((((melt_amounts[id].replace('\n', '')).replace('  ',',')).replace(' -',',-')).replace(' ', ',')).replace('[,','[')).replace(',,',',')))
    # meltingheats = np.array(ast.literal_eval(((melt_heats[id].replace('\n', '')).replace(' ',','))))
    meltingnames = melt_names[id]
    meltingamounts = melt_amounts[id]
    meltingheats = melt_heats[id]
    meltingheats_names = meltingheats[:,0]
    amountmelted = 0
    
    for subid in range(len(meltingnames)):
        oxidename = meltingnames[subid]
        oxideamount = meltingamounts[subid]
        oxide_meltingtemp = meltingheats[np.where(meltingheats_names == oxidename)][0][1]
        keys = np.asarray(list(chemparse.parse_formula(oxidename).keys()))
        values = np.asarray(list(chemparse.parse_formula(oxidename).values()))
        masses = []
        for i in keys:
            masses.append(periodictable[:,7][np.argwhere(periodictable[:,0]==i)])
        masses = np.array(masses)
        oxidemass = np.dot(masses.T, values) * oxideamount
        if np.float(material_meltingtemp) > np.float(oxide_meltingtemp):
            amountmelted += oxidemass
    
   
    meltingmass.append(amountmelted)



C:\Users\songo\AppData\Local\Temp\ipykernel_16848\3703799358.py:24: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if np.float(material_meltingtemp) > np.float(oxide_meltingtemp):


In [262]:
meltingmass = np.array(meltingmass)
netmass = np.array(netmass)

C:\Users\songo\AppData\Local\Temp\ipykernel_16848\1943670075.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  meltingmass = np.array(meltingmass)


In [263]:
percentmelted = []
for id in range(len(meltingmass)):
    percentmelted.append(meltingmass[id]/netmass[id])


In [264]:
percentmelted = np.array(percentmelted)

In [265]:
np.max(percentmelted)

3.3281563078334235

In [268]:
len(np.where(percentmelted[:,0][:,0] > 1)[0])

230

In [267]:
percentmelted[:,0][:,0][0:20]

array([0.972598802111982, 0.0010978015183133304, 1.0452173730388763,
       0.876888166592377, 0.8648347542008691, 0.3312656965127197,
       0.003474072295642506, 1.12176823289425, 0.21698544853072807,
       0.4485378364958925, 0.21348624102429592, 0.862713538973544,
       3.7284173522795376e-08, 1.4504889156167557, 1.3193390143154284,
       1.6760354282911636, 1.2044388520430567, 0.2586151282525346,
       1.3051333135730487, 0.024941228715051982], dtype=object)